#!/bin/sh
PKG_NAME=alwaysonline
[ -x "$(command -v nft)" ] && FW='fw4' || FW='fw3'

uci -q batch <<-EOF
	delete firewall.${PKG_NAME}
	set firewall.${PKG_NAME}=include
	set firewall.${PKG_NAME}.type=script
	set firewall.${PKG_NAME}.path=/usr/share/${PKG_NAME}/$FW.include
	commit firewall
EOF
if [ "$FW" == "fw3" ]; then
uci -q batch <<-EOF
	set firewall.${PKG_NAME}.family=any
	set firewall.${PKG_NAME}.reload=1
	commit firewall
EOF
fi
